flask_app/flaskapp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, IntegerField
from wtforms.validators import DataRequired, Length, Email, ValidationError
from flaskapp.models import User

class RegistrationForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=2, max=25)])
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("That username is taken. Please choose another one.")

class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=2, max=25)])
    remember = BooleanField("Remember me")
    submit = SubmitField("Login")

class UpdateAccountForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(min=2, max=25)])
    survey_token = StringField('Survey Token', validators=[DataRequired()])
    submit = SubmitField("Update")

flask_app/flaskapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flaskapp.config import Config


db = SQLAlchemy()
login_manager = LoginManager() # Handles login sessions. Makes it super easy
login_manager.login_view = "users.login" # It is the name of the login function



def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)

    from flaskapp.users.routes import users
    from flaskapp.main.routes import main

    app.register_blueprint(users)
    app.register_blueprint(main)

    return app

flask_app/flaskapp/main/routes.py
from flask import render_template, Blueprint


main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template("home.html")


@main.route("/admin")
def admin():
    return render_template("admin.html", title="Admin")

flask_app/flaskapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, send_file
from flask_login import login_user, current_user, logout_user, login_required
from flaskapp import db
from flaskapp.models import User 
from flaskapp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from flaskapp.algorithms import AlgorithmSolutions
import json
import os

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if current_user.is_authenticated:   # If user is already logged in
        return redirect(url_for("main.home")) 
    if form.validate_on_submit():
        user1 = User(username=form.username.data)
        #print(User.query.all())
        db.session.add(user1)
        db.session.commit()
        flash(f"Dear {form.username.data}, your account has successfully been created account! Please login to continue.", "success")
        return redirect(url_for("main.home"))
    return render_template("register.html", title="Register", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    if form.validate_on_submit():
        user1 = User.query.filter_by(username=form.username.data).first()
        if user1:
            login_user(user1, remember=form.remember.data)
            attempted_access = request.args.get("next") # passes in "/ATTEMPTED_ACCESS_PAGE_NAME"
            if attempted_access:
                flash("You have successfully logged in!", "success")
                return redirect(attempted_access)
            else:
                flash("You have successfully logged in!", "success")
                return redirect(url_for("main.home"))
        else:
            flash("Your login was unsuccessful. Please check your username", "danger")
    return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@users.route("/account", methods=["GET", "POST"])
@login_required # Ensures that in order to access this page, you need to login
def account():
    form = UpdateAccountForm()
    #print(User.query.all())

    if form.survey_token.data:
        sols = AlgorithmSolutions()
        current_user.username = current_user.username
        current_user.survey_token = form.survey_token.data
        current_user.survey_cheat = sols.is_cheating(current_user.survey_token)
        current_user.survey_clicks = sols.num_clicks(current_user.survey_token, current_user.survey_cheat)
        db.session.commit()
        flash("Updated!", "success")
        return redirect(url_for("main.home"))
    elif request.method == "GET":
        form.survey_token.data = current_user.survey_token
    return render_template("account.html", title="Account", form=form)

@users.route("/download")
def download():
    user_list = User.query.all()
    user_hashtable = {}
    for i in range(len(user_list)):
        user_node = user_list[i]
        user_hashtable[user_node.username] = {"Survey Type": user_node.survey_type,
                                              "Survey Token": user_node.survey_token,
                                              "Survey Cheat": user_node.survey_cheat,
                                              "Survey Clicks": user_node.survey_clicks
                                              }
    directory = os.getcwd()
    print(directory)
    with open(f"{directory}/flaskapp/SurveyData.json", "w") as file:
        json.dump(user_hashtable, file)
    return send_file('SurveyData.json', attachment_filename='SurveyData.json', as_attachment=True, cache_timeout=0)
    
    return redirect(url_for("main.home"))

flask_app/flaskapp/templates/admin.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <fieldset class="form-group">
            <h1> Data Retrieval </h1>
            <p>
                Hi Professor, <br/> <br/>
                In order to download the most up-to-date data, please click the "Download" button below. <br /> <br />
                Please keep in mind that the data is currently being stored in a JSON format. <br /> <br />
    
                Warm Regards, <br /> <br />
    
                Aditya
            </p>
            <a href="{{ url_for('users.download') }}" target="_blank"><button class='btn btn-outline-info'>Download!</button></a>    
        </fieldset>
    </div>
{% endblock %}

flask_app/flaskapp/templates/home.html
{% extends "layout.html" %} <!-- All files are given w/ reference to folder names static & template -->
{% block content %}
    <div class="content-section">
        {% if current_user.is_authenticated %}
            <div class="border-bottom mb-4">
                <h1> Dear {{ current_user.username }}, </h1>
            </div>
            <div>
                <div class="content-section">
                    <h5> Step 1 - Information</h5>
                    <p> 
                        In order to participate in this survey, you will have recieved a Qualtrics Survey Link in your email.
                        Unfortunately, if you didn't recieve a link then you are ineligible to participate. 
                    </p>
                 </div>
                 <div class="content-section">
                    <h5> Step 2 - Sign Up </h5>
                    <p> 
                        To register your account, please click the "Register" icon at the top of the nav bar.
                        When selecting a username, please select a username that is completely random. Do not include any identifying pieces of information in your username (name, nickname, company etc...)
                        If any username contains any identifying piece of information, all information related to it will be discarded and the respective individual's participation will be nullified.
                    </p>
                    <p>  </p>

                 </div>
                 <div class="content-section">
                    <h5> Step 1 - Data Experiment </h5>
                    <p> 
                        Congragulations! If you are here, you have successfully set up your account!
                        Please click the "Experiment" link at the nav-bar to begin your Experiment.
                        
                        The goal of the experiment is for you to answer the following question "INSERT_QUESTION?"
                        Once you have arrived at your conclusion, execute the following instructions
                        <ul>
                            <li> Scroll to the bottom of the page </li>
                            <li> Click on the "Generate Your Survey Token" button </li>
                            <li> Scroll even further down. </li>
                            <li> Notice a series of numbers seperated by spaces. This is your survey token. </li>
                            <li> Write down only the numbers and proceed to Step 4</li>
                        </ul>
                    </p>
                 </div>
                 <div class="content-section">
                    <h5> Step 4 - Experiment Completion </h5>
                    <p> 
                        At this stage, you should have your Survey Token. <br />
                        If you do not have your Survey Token, please return to Step 3 and follow the instructions carefully. <br />
                        However, in the event that you clicked the Survey Token and no token appeared below, please use the following Safety Token "0"
                        
                        To continue, please execute the following steps precisely.
                        <ul>
                            <li> Click on "Account" in the Nav-Bar </li>
                            <li> In the "Account Info" section, input only the numbers from your Survey Token. If you are using the Safety Token, please input "0".  </li>
                            <li> Click Update </li>
                            <li> Proceed to Step 5</li>
                        </ul>
                    </p>
                 </div>
                 <div class="content-section">
                    <h5> Step 5 - Qualtrics Return</h5>
                    <p> 
                        Congragulations {{ current_user.username }}! You have successfully completed 75% of the Experiment. Please return to the Qualtrics Survey Tab and continue with the Survey.
                    </p>
                 </div>
            </div>
        {% else %}
        <div class="border-bottom mb-4">
            <h1> Dear Visitor, </h1> 
        </div>
            <p> Welcome to the Data Analysis Site. </p>
            <p> If this is your first time here, please click on the following hyperlink to generate and register your username: <a class="ml-2" href="{{ url_for('users.register') }}">Register</a></p>
	    <p> Once you have registered your account, please click on the following hyperlink to login and follow the next series of instructions: <a class="ml-2" href="{{ url_for('users.login') }}">Login</a></p>
        {% endif %}
    </div>
{% endblock content %}

flask_app/flaskapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        {% if title %}
            <title>Big Data Experiment - {{ title }}</title>
        {% else %}
            <title>Big Data Experiment</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Big Data Experiment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                  </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">

                    {% if current_user.is_authenticated %}
                      {% if current_user.username == "AdminDeveloper" %}
                        <a class="nav-item nav-link" href="{{ url_for('main.admin') }}" target="_blank"/>Admin</a>
                      {% endif %}

                      {% if current_user.survey_type == 1 %}
                        <a class="nav-item nav-link" href=https://ldd1.herokuapp.com target="_blank"/>Experiment</a>
                      {% else %}
                        <a class="nav-item nav-link" href=https://bdd1.herokuapp.com target="_blank"/>Experiment</a>
                      {% endif %}
                      
                      <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                      <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                      <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                      <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </nav>
        </header>
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}
        
            {% endblock %}
        </div>
        
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html> 

flask_app/flaskapp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login Now</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} 
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flask_app/flaskapp/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=""> <!-- Setting it to "" means to return the POSTED information to the same route -->
            {{ form.hidden_tag() }} <!-- Prevents CSFA -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register Now</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label")}}

                    {% if form.username.errors %} <!-- A boolean that checks if any conditions were broken. Broken ones are tagged as errors-->
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }} <!--This is the display of the form entry-->
                        <small id="uniqueUsername" class="form-text text-muted">To keep it anonymous, do not use any identifying piece of information i.e name, nickname etc...</small>
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top-pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Login</a>
        </small>
    </div>
{% endblock content %}